### ISSUE TITLE
Doesn't work with CB 1.2.3R0.1

### ISSUE THREAD

**Issue by mmichaa** [ltguide/CraftBukkit-MineBackup#23]
Got the following error while starting the server:

```
$ ./craftbukkit.sh 
177 recipes
27 achievements
14:36:39 [INFO] Starting minecraft server version 1.2.3
14:36:39 [INFO] Loading properties
14:36:39 [INFO] Starting Minecraft server on *:25565
14:36:39 [INFO] This server is running CraftBukkit version git-Bukkit-1.1-R6-33-gb66156b-b2034jnks (MC: 1.2.3) (Implementing API version 1.2.3-R0.1)
14:36:39 [INFO] [MineBackup] Loading MineBackup v0.5.5
14:36:39 [INFO] Preparing level "world"
14:36:39 [INFO] Default game type: 0
14:36:39 [INFO] Preparing start region for level 0 (Seed: 7213756717555472698)
14:36:40 [INFO] Preparing spawn area: 85%
14:36:41 [INFO] Preparing start region for level 1 (Seed: 7213756717555472698)
14:36:41 [INFO] Preparing spawn area: 97%
14:36:41 [INFO] Preparing start region for level 2 (Seed: 7213756717555472698)
14:36:42 [INFO] [MineBackup] Enabling MineBackup v0.5.5
14:36:42 [SCHWERWIEGEND] Error occurred while enabling MineBackup v0.5.5 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:234)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:37)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at ltguide.minebackup.MineBackup.onEnable(MineBackup.java:50)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:363)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:374)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:361)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 26 more
14:36:42 [INFO] Server permissions file permissions.yml is empty, ignoring it
14:36:42 [INFO] Done (2,809s)! For help, type "help" or "?"
```

**Comment by dredhorse** [comment]
try 0.5.7 which is on the comments and has FTP and R5 support..

**Comment by mmichaa** [comment]
Thanks! Seems to work. Don't get this exception anymore.
The Link: https://github.com/dredhorse/CraftBukkit-MineBackup/tree/master/plugin

**Comment by dredhorse** [comment]
I just hope that the original developer comes back soon
